module.exports = {
    LOGIN: 1,
    LOGIN_RESULT_ERROR: 2,
    LOGIN_RESULT_SUCCESS: 3,
    GLOB_PLAYER_COUNT: 4,
    ENTITY_LIST: 5,
    ENTITY_ADD: 6,
    ENTITY_REMOVE: 7,
    ENTITY_TELEPORT: 8,
    CLIENT_MOVE_UPDATE: 9,
    SERVER_MOVE_UPDATE: 10
};