module.exports = {
    LOGIN: 1,
    LOGIN_RESULT_ERROR: 2,
    LOGIN_RESULT_SUCCESS: 3,
    GLOB_PLAYER_COUNT: 4,
    ENTITY_LIST: 5,
    ENTITY_ADD: 6,
    ENTITY_REMOVE: 7,
    ENTITY_TELEPORT: 8,
    CLIENT_MOVE_UPDATE: 9,
    SERVER_MOVE_UPDATE: 10,
    CLIENT_CHAT: 11,
    SERVER_CHAT: 12,
    LOAD_MAP: 13,
    MAP_LOADED: 14,
    CLIENT_ATTACK: 15,
    SERVER_ATTACK: 16,
    DAMAGE_ENTITY: 17
};